config/routes.rb
Looter::Application.routes.draw do |map|
  devise_for :users

  root :to => "campaigns#index"

  resources :campaigns do
    resources :loots
  	resources :notes
    resources :characters do
      member do
        get :update_hit_points
      end
      resources :stats
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_taggable
  belongs_to :campaign
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :assure_loggon
  before_filter :get_campaign
  before_filter :get_tag_cloud, :only=>[:index]

  # GET /notes
  # GET /notes.xml
  def index
    tag_name = params.delete :tag
    unless tag_name.blank?
      @notes = @campaign.notes & Note.tagged_with(tag_name)
    else
      @notes = @campaign.notes
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
#    tags = params[:note].delete(:tag_list)
    @note = Note.new(params[:note])        
#    @campaign.notes.tag_list = tags

    respond_to do |format|
      if @campaign.notes << @note
        format.html { redirect_to([@campaign,@note], :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        if params[:continue]
          flash[:notice] = "Saved!"
          format.html { render :action => "edit" }
        else  
          format.html { redirect_to([@campaign,@note], :notice => 'Note was successfully updated.') }
        end
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(campaign_notes_url(@campaign)) }
      format.xml  { head :ok }
    end
  end


  def get_tag_cloud
    #@tags = Note.tag_counts_on(:tags)
    @tags = get_tags_count_on(Note)
    # query = <<-SQL
    # SELECT tags.*, COUNT(*) AS count 
    # FROM tags
    # LEFT OUTER JOIN taggings ON tags.id = taggings.tag_id AND taggings.context = 'tags' 
    # INNER JOIN notes ON notes.id = taggings.taggable_id 
    # WHERE  (taggings.taggable_type = 'Note') AND (taggings.taggable_id IN(SELECT notes.id FROM notes)) 
    # GROUP BY  tags.id, tags.name 
    # HAVING COUNT(*) > 0
    # SQL
    # @tags = ActsAsTaggableOn::Tag.find_by_sql(query)
    
  end

  
end

app/helpers/notes_helper.rb
module NotesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/notes/_form.html.erb
<%= form_for([@campaign, @note]) do |f| %>
  <% if @note.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>
    <ul>
    <% @note.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br />
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :texte %><br />
    <%= f.text_area :texte %>
  </div>
  <div class="field">
  <%= f.label :tags %>
  <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %><%= f.submit("Save and continue", :name=>"continue") unless @note.id.blank?%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<div id='edit_notice'>
<%= flash[:notice]%>
</div>

<%= render 'form' %>

<%= link_to 'Show', [@campaign,@note] %> |
<%= link_to 'Back', campaign_notes_path(@campaign) %>

<%=javascript_tag "$('#edit_notice').fadeOut(2000);" %>

app/views/notes/index.html.erb
<div>
<h1>Notes</h1>
<div class="center_column">
  <table>
    <tr>
      <th>Titre</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @notes.each do |note| %>
    <tr>
      <td><%= link_to note.titre, [@campaign, note] %></td>
      <td><%= note.created_at.strftime "%Y-%m-%d" %></td>
      <td><%= link_to 'Show', [@campaign, note] %></td>
      <td><%= link_to 'Edit', edit_campaign_note_path(@campaign, note) %></td>
      <td><%= link_to 'Destroy', [@campaign, note], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Note', new_campaign_note_path(@campaign) %>
</div>
<div class="side_column">
  <p>Tags:</p>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name, campaign_notes_path(@campaign, :tag=>tag.name), :class => css_class %>
  <% end %>
  <p>
    <%= link_to 'all', campaign_notes_path(@campaign) %>
  </p>
</div>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>
<a href="http://redcloth.org/textile/writing-paragraph-text/" target="_blank">? textile</a>
<%= render 'form' %>

<%= link_to 'Back', campaign_notes_path(@campaign) %>

app/views/notes/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Titre:</b>
  <%= @note.titre %>
</p>

<p>
  <b>Texte:</b>
<div style="padding: 10px; border: 1px solid #888;">
  <%=raw RedCloth.new(sanitize @note.texte).to_html %>
</div>
</p>

<p>
  <b>Tags:</b>
  <%= @note.tag_list.join ',' %>
</p>



<%= link_to 'Edit', edit_campaign_note_path(@campaign,@note) %> |
<%= link_to 'Back', campaign_notes_path(@campaign) %>