config/routes.rb
Looter::Application.routes.draw do |map|
  devise_for :users

  root :to => "campaigns#index"

  resources :campaigns do
    resources :loots
  	resources :notes
    resources :characters do
      member do
        get :update_hit_points
      end
      resources :stats
    end
  end

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :campaign
  has_many :stats, :order=>:name
  
  def stats_by_categories
    categories = {}
    self.stats.each do |stat|
      categories[stat.category] ||= []
      categories[stat.category] << stat
    end
    categories
  end
  
  
  class << self
    def user_campaign(user, campaign)
      Character.find_by_campaign_id_and_user_id(campaign.id, user.id)    
    end
  end
  
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :assure_loggon
  before_filter :get_campaign

  # GET /characters
  # GET /characters.xml
  def index
    @characters = @campaign.characters

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.xml
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.xml
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.xml
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to([@campaign, @character], :notice => 'Character was successfully created.') }
        format.xml  { render :xml => @character, :status => :created, :location => @character }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.xml
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        if params[:continue]
          flash[:notice] = "Saved!"
          format.html { render :action => "edit" }
        else  
          format.html { redirect_to([@campaign, @character], :notice => 'Character was successfully updated.') }
        end
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.xml
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to(campaign_characters_url(@campaign)) }
      format.xml  { head :ok }
    end
  end
  
  def update_hit_points
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for([@campaign, @character]) do |f| %>
  <%= f.error_messages %>

    Campaign: <%= @campaign.title %><br /><br />
    <%= hidden_field_tag 'character[campaign_id]', @campaign.id %>
    <%= hidden_field_tag 'character[user_id]', current_user.id %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :class %><br />
    <%= f.text_field :character_class %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :original_hit_points %><br />
    <%= f.text_area :original_hit_points %>
  </div>
  
  <div class="actions">
    <%= f.submit %><%= f.submit("Save and continue", :name=>"continue") unless @character.id.blank?%>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>
<div id='edit_notice'>
<%= flash[:notice]%>
</div>

<%= render 'form' %>

<%= link_to 'Show', [@campaign, @character] %> |
<%= link_to 'Back', campaign_characters_path(@campaign) %>

<%=javascript_tag "Element.fade('edit_notice', {duration:2});" %>

app/views/characters/index.html.erb
<h1>Characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Class</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= link_to character.name, [@campaign, character] %></td>
    <td><%= character.character_class %></td>
    <td><%= link_to "*", "#", :title=>character.description, :style=>"text-decoration: none" unless character.description.blank? %></td>
    <td><%= link_to 'Show', [@campaign, character] %></td>
    <td><%= link_to 'Edit', edit_campaign_character_path(@campaign, character) %></td>
    <td><%= link_to 'Destroy', [@campaign, character], :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'stats', campaign_character_stats_path(@campaign, character) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_campaign_character_path(@campaign) %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', campaign_characters_path(@campaign) %>

app/views/characters/show.html.erb
<% categories = @character.stats_by_categories%>

<div>
  <p>
    <b>Name:</b>
    <%= @character.name %>
  </p>
  <hr/>
  <div>
    <p>
      <b>Original hit points:</b><%= @character.original_hit_points %>
        <%= form_for([@campaign, @character], :html=>{:id=>:current_hit_points_form}, :remote=>true) do |f| %>        
        <div class="field">
          <b><%= f.label :current_hit_points %></b>
          <%= f.text_area :current_hit_points, :id=>:current_hit_points, :style=>"width: 600px, height: 200px;" %>
        </div>
        
      <%end%>
      <script language="JavaScript">
      var old_var = $("#current_hit_points").val();
      window.setInterval('if(old_var!=$("#current_hit_points").val()){$("#current_hit_points_form").submit();old_var = $("#current_hit_points").val();}', 500);
      </script>
    </p>
  <hr/>
    <div class="menu short padding_bottom_20">	
  		<ul>
        <li><%=link_to 'description', "#", :onclick=>"toggle_stats('description');return false;" %></li>
        <% categories.keys.each do |category|%>
          <li><%=link_to category, "#", :onclick=>"toggle_stats('#{category}');return false;" %></li>
        <%end%>
        
      </ul>
    </div>
    <% categories.each_pair  do |category, stats|%>
      <% content_tag(:div, :id=>"category_#{category}", :class=>"stats_category") do%>
        <p><b><%=category%></b></p>
        <table class="stats">
          <tr>
            <th>Name</th>
            <th>Value</th>
            <th>bonus</th>
            <th>temp bonus</th>
            <th>Original</th>
            <th></th>
          </tr>

          <% stats.each do |stat| %>
            <tr>
              <td><%= stat.name %></td>
              <td><%= stat.value %></td>
              <td><%= stat.permanent_bonus %></td>
              <td><%= stat.temporary_bonus %></td>
              <td><%= stat.original_value %></td>
              <td><%= link_to "*", "#", :title=>stat.description unless stat.description.blank? %></td>
            </tr>
          <% end %>
        </table>
      <% end %>
    <%end%>
      
    <div id="category_description" class="stats_category" style="display:block">
      
      <p>
        <b>Class:</b>
        <%= @character.character_class %>
      </p>
      <p>
        <b>Description:</b>
        <%=raw RedCloth.new(sanitize @character.description).to_html %>
      </p>
    </div>
      
</div>


<%= link_to 'Edit', edit_campaign_character_path(@campaign, @character) %> |
<%= link_to 'Back', campaign_characters_path(@campaign) %> | 
<%= link_to 'stats', campaign_character_stats_path(@campaign, @character) %>