config/routes.rb
Looter::Application.routes.draw do |map|
  devise_for :users

  root :to => "campaigns#index"

  resources :campaigns do
    resources :loots
  	resources :notes
    resources :characters do
      member do
        get :update_hit_points
      end
      resources :stats
    end
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :notes, :dependent => :destroy
  has_many :loots, :dependent => :destroy
  has_many :characters, :dependent => :destroy
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.xml
  before_filter :assure_loggon
  
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.xml
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.xml
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.xml
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to(@campaign, :notice => 'Campaign was successfully created.') }
        format.xml  { render :xml => @campaign, :status => :created, :location => @campaign }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @campaign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.xml
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to(@campaign, :notice => 'Campaign was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @campaign.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.xml
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to(campaigns_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>
    <ul>
    <% @campaign.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<h1>Campaigns</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @campaigns.each do |campaign| %>
  <tr>
    <td style="padding-right: 20px;"><%= campaign.title %></td>
	  <td><%= link_to 'Notes', campaign_notes_path(campaign)%></td>
	  <td><%= link_to 'Loot', campaign_loots_path(:campaign_id=>campaign)%>&nbsp;&nbsp;&nbsp;</td>
	  <td style="padding-right: 20px;"><%= link_to 'Characters', campaign_characters_path(:campaign_id=>campaign)%>&nbsp;&nbsp;&nbsp;</td>
    <td><%= link_to 'Show', campaign %></td>
    <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
    <td><%= link_to 'Destroy', campaign, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= sanitize @campaign.title %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>