config/routes.rb
Looter::Application.routes.draw do |map|
  devise_for :users

  root :to => "campaigns#index"

  resources :campaigns do
    resources :loots
  	resources :notes
    resources :characters do
      member do
        get :update_hit_points
      end
      resources :stats
    end
  end

end

app/models/stat.rb
class Stat < ActiveRecord::Base
  belongs_to :character

  class << self
    def create_quick_stat(character, quick_stat)
      begin 
        stats = []
        stats_arr = quick_stat.gsub(/,/, "\n").split("\n")
        stats = stats_arr.map do |stat| 
          fields = stat.split(':') 
          {:name=>fields[0].strip, :value=>fields[1].strip, :category=>fields[2].strip, :character_id=>character.id}
        end
        create stats
      rescue Exception => e
        raise Exception.new("invalid quick_stats format")
      end
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_filter :get_campaign
  before_filter :get_character

  # GET /stats
  # GET /stats.xml
  def index
    @stats = @character.stats.all(:order=>[:category, :name])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stats }
    end
  end

  # GET /stats/1
  # GET /stats/1.xml
  def show
    @stat = Stat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @stat }
    end
  end

  # GET /stats/new
  # GET /stats/new.xml
  def new
    @stat = Stat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @stat }
    end
  end

  # GET /stats/1/edit
  def edit
    @stat = Stat.find(params[:id])
  end

  # POST /stats
  # POST /stats.xml
  def create
    if params[:stat]
      @stat = Stat.new(params[:stat].merge(:character_id=>@character.id))

      respond_to do |format|
        if @stat.save
          format.html { redirect_to(campaign_character_stats_url(@campaign, @character)) }
          format.xml  { render :xml => @stat, :status => :created, :location => @stat }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @stat.errors, :status => :unprocessable_entity }
        end
      end
    elsif params[:quick_stat]
      begin
        Stat.create_quick_stat(@character, params[:quick_stat])
        respond_to do |format|
          format.html { redirect_to(campaign_character_stats_url(@campaign, @character)) }
          format.xml  { head :ok }
        end
      rescue Exception=>e
        flash[:error] = e.message  
        respond_to do |format|
          format.html { redirect_to(campaign_character_stats_url(@campaign, @character)) }
          format.xml  { head 400 }
        end
      end
    end
  end

  # PUT /stats/1
  # PUT /stats/1.xml
  def update
    @stat = Stat.find(params[:id])

    respond_to do |format|
      if @stat.update_attributes(params[:stat])
        format.html { redirect_to(campaign_character_stats_url(@campaign, @character)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @stat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.xml
  def destroy
    @stat = Stat.find(params[:id])
    @stat.destroy

    respond_to do |format|
      format.html { redirect_to(campaign_character_stats_url(@campaign, @character)) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_for([@campaign, @character, @stat]) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :permanent_bonus %><br />
    <%= f.text_field :permanent_bonus %>
  </div>
  <div class="field">
    <%= f.label :temporary_bonus %><br />
    <%= f.text_field :temporary_bonus %>
  </div>
  <div class="field">
    <%= f.label :original_value %><br />
    <%= f.text_field :original_value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing stat</h1>

<%= render 'form' %>

<%= link_to 'Show', campaign_character_stat_path(@campaign, @character,@stat) %> |
<%= link_to 'Back', campaign_character_stats_path(@campaign, @character) %>

app/views/stats/index.html.erb
<h1>stats</h1>

<%form_for :stat, [@campaign, @character] do |form|%>
  <p>
    Quick stat, Create several stats at once, specify the name, value and category separated by columns, separate each stat by periods.<br/> ex: name:value:category, name2:value2:category2<br/>
    <%= text_area_tag :quick_stat %>
  </p>
  <%=form.submit "Create quick stats"%>
<%end%>

<br />

<%= link_to 'Create New Stat', new_campaign_character_stat_path(@campaign, @character) %>


<table>
  <tr>
    <th>Stat</th>
    <th>Value</th>
    <th>bonus</th>
    <th>temp bonus</th>
    <th>Original</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stats.each do |stat| %>
  <tr>
    <td><%= stat.name %></td>
    <td><%= stat.value %></td>
    <td><%= stat.permanent_bonus %></td>
    <td><%= stat.temporary_bonus %></td>
    <td><%= stat.original_value %></td>
    <td><%= stat.category %></td>
    <td><%= link_to "*", "#", :title=>stat.description unless stat.description.blank? %></td>
    <td><%= link_to 'Show', [@campaign, @character, stat] %></td>
    <td><%= link_to 'Edit', edit_campaign_character_stat_path(@campaign, @character, stat) %></td>
    <td><%= link_to 'Destroy', [@campaign, @character, stat], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stat', new_campaign_character_stat_path(@campaign, @character) %>

app/views/stats/new.html.erb
<h1>New stat</h1>

<%= render 'form' %>

<%= link_to 'Back', campaign_character_stats_path(@campaign, @character) %>

app/views/stats/show.html.erb
<p>
  <b>name</b>
  <%= @stat.name %>
</p>
<p>
  <b>value</b>
  <%= @stat.value %>
</p>
<p>
  <b>permanent_bonus</b>
  <%= @stat.permanent_bonus %>
</p>
<p>
  <b>temporary_bonus</b>
  <%= @stat.temporary_bonus %>
</p>
<p>
  <b>original_value</b>
  <%= @stat.original_value %>
</p>
<p>
  <b>description</b>
  <%= @stat.description %>
</p>
<p>
  <b>category</b>
  <%= @stat.category %>
</p>
<%= link_to 'Edit', edit_campaign_character_stat_path(@campaign, @character,@stat) %> |
<%= link_to 'Back', campaign_character_stats_path(@campaign, @character) %>